name: Bug 报告
description: 报告项目使用中遇到的问题
title: "[Bug]: "
labels: ["bug", "待处理"]
body:
  - type: markdown
    attributes:
      value: |
        ## 感谢你的反馈!
        请填写以下信息以帮助我们更快定位问题。
  
  - type: checkboxes
    id: checklist
    attributes:
      label: 提交前确认
      options:
        - label: 我已经搜索过现有的 issues,确认这不是重复问题
          required: true
        - label: 我已经阅读过项目文档
          required: true
  
  - type: dropdown
    id: latest-version
    attributes:
      label: 是否是最新版
      description: 请确认你使用的是否是最新版本
      options:
        - 是,使用最新版
        - 否,使用旧版本
    validations:
      required: true
  
  - type: input
    id: channel
    attributes:
      label: 调用的是哪个渠道
      description: 例如 geminicli 或者 antigravity
      placeholder: "例如: geminicli"
    validations:
      required: true
  
  - type: input
    id: model
    attributes:
      label: 调用的是哪个模型
      description: 例如 gemini-2.5-flash
      placeholder: "例如: gemini-2.5-flash"
    validations:
      required: true
  
  - type: dropdown
    id: format
    attributes:
      label: 调用的是哪个格式
      description: 选择你使用的 API 格式
      options:
        - gemini 格式
        - openai 格式
        - claude 格式
        - 其他格式
    validations:
      required: true
  
  - type: textarea
    id: error-content
    attributes:
      label: 具体报错内容
      description: 请粘贴完整的错误信息或截图
      placeholder: |
        请在这里粘贴完整的错误日志或堆栈信息
      render: shell
    validations:
      required: true
  
  - type: textarea
    id: error-description
    attributes:
      label: 错误描述
      description: 详细描述问题的发生场景、预期行为和实际行为
      placeholder: |
        1. 我在做什么操作时遇到了这个问题
        2. 我期望的结果是...
        3. 但实际上发生了...
    validations:
      required: true
  
  - type: textarea
    id: additional-context
    attributes:
      label: 补充信息(可选)
      description: 其他任何有助于解决问题的信息
      placeholder: 例如:操作系统、Python 版本、相关配置等